apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: demo-jenkins
  name: demo-jenkins
  namespace: myproject
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    #pushSecret:
    #  name: ci00983051-prom
    to:
      kind: DockerImage
      name: avrylkov/demo-jenkins:${project.version}
  postCommit: {}
  resources:
    limits:
      memory: 756Mi
    requests:
      memory: 512Mi
  runPolicy: Serial
  source:
    git:
      ref: release
      uri: 'https://github.com/avrylkov/demo-jenkins.git'
    #sourceSecret:
    #  name: openshift-git-secret-key
    type: Git
  strategy:
    dockerStrategy:
      env:
        - name: version
      from:
        kind: DockerImage
        name: 'redhat-openjdk18-openshift:1.3'
    type: Docker
  successfulBuildsHistoryLimit: 5